### ISSUE TITLE
about the PMM model

### ISSUE THREAD

**Issue by REDXXXX** [siFeiden/PMM#3]
I have read your code  of PMM algorithm.The annotation in the code is good, but I still get some questions.
1. Do we initalize the PMM instance for each user?
2, Can you offered a demo of how to use the PMM code the predict user's trajectory?
3. What's the performence of your PMM algorithm compared to the user's model?
I would appreciate it a lot if you could answer my questions.Best wishes to you.

**Comment by siFeiden** [comment]
1. Yes, you need a new PMM instance for each user. Every user has her own location history that must be passed to the constructor of the PMM. You use it as follows:
```java
List<ILocation> locationHistory = ...; // get the user's location history from somewhere
ILocation predictLocation = ...; // find a location you want to get a prediction for
Pmm pmm = new Pmm(locationHistory);
double locationProbability = pmm.estimateNextLocationProbability(predictLocation); // probability that user will be next in the given location
```
2. You can find information about the performance of the PMM model in the paper 'Friendship and Mobility: User Movement In Location-Based Social Networks' by Cho et al.

**Comment by REDXXXX** [comment]
Thank you for your response!It helps me a lot!
Best wishes to you!
